/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;

import edu.isu.cs.cs2263.schedule.Course;
import edu.isu.cs.cs2263.schedule.Student;

import java.util.ArrayList;
import java.util.List;

public class App {

    public static void main(String[] args) {

    }

}
